### PR TITLE
Add Spinner

### PR DESCRIPTION
**Pull request by octycs**
out

That's a simple semi circle spinner. The gif is not that fluent because of my computer.

Should I add the compiled files (`loaders.css` etc.)?

### CODE REVIEW

**Comment by ConnorAtherton** [comment]
Nice! Yeah, can you run the gulp task and add the compiled files. Thanks.

**Comment by octycs** [comment]
No problem.

**Comment by octycs** [comment]
They don't seem to be good. I'll fix that.

**Comment by octycs** [comment]
Now it works.

**Comment by ConnorAtherton** [comment]
Thanks @octycs. I had to move `border-radius: 100%' to the child div to get the semi-circle but looks great :)

**Comment by octycs** [comment]
Cool, thanks! :smile:

**Pull request merged**
