### PR TITLE
Created mixins and fixes missing cross-browsers prefixes

### PR DESCRIPTION
**Pull request by marcelaraujo**
I did some changes as introduce mixins to generate cross-browsers prefixes and fixes some missing styles too. When I built on my local machine, the demo wasn't running as I expected and as demo on your site.

Thanks

### CODE REVIEW

**Comment by ConnorAtherton** [comment]
Hello @marcelaraujo, what was wrong with the demo?

This project uses autoprefixer to add the prefixes automatically. The lowest supported is currently set to IE8 but I want to bump that up to IE9 soon. A gulpfile.js isn't created so it shouldn't be added to the .gitignore. 

I don't want to merge this because we are already adding prefixes. Can you let me know what wasn't working and we can figure out how to fix that. Thanks.

**Comment by marcelaraujo** [comment]
I saw autoprefixer plugin but it doesn't generate all prefixes that we should support. If you build on local machine, you'll see that generate file is missing -webkit prefix.

If autoprefix works as you said, so why did you add -webkit prefix on this file?

https://github.com/ConnorAtherton/loaders.css/blob/master/src/animations/ball-pulse-round.scss#L10

**Comment by marcelaraujo** [comment]
@ConnorAtherton 

The problem exists when I import your library as SASS component. The browser prefixes won't will exists because I won't use autoprefixer grunt plugin.

**Comment by ConnorAtherton** [comment]
Closing this now, I don't want to add prefixes in two different places. There was a long discussion about how to handle vendor prefixes [here](https://github.com/ConnorAtherton/loaders.css/issues/18) and I'm going to stand by my decision in that case. 

In your case, if you are using SCSS and importing the files then it is your decision whether to add prefixes or not in your build system. Nonetheless, I just want to thank you for taking the time to add some value to this project by kicking off this discussion again. It's definitely something to consider for future projects.

**Comment by marcelaraujo** [comment]
Ok.

It's your project. Do as you want to.

;)

**Pull request closed without merging**
