### PR TITLE
Added JS to populate `.loader-inner`s

### PR DESCRIPTION
**Pull request by corysimmons**
Cool library. I wouldn't actually use it if I had to manually insert a random number of divs into an element.

1. It clutters development markup
1. It's hard to remember how many divs go into XYZ

This PR fixes that.

### CODE REVIEW

**Comment by ConnorAtherton** [comment]
Hi @corysimmons, thanks for this. I agree that your implementation is much easier, could you re-structure the README to clarify that adding loaders.js is optional? 

I need to modify gulp to minify each individual animation and intend to include the exact structure of the DOM element there so people can copy and paste it.

**Comment by corysimmons** [comment]
Sure. Does this work?

**Comment by ConnorAtherton** [comment]
Yep, that's great, thanks for this :+1: :)

**Comment by corysimmons** [comment]
No problem. Love Walkway as well. Thanks for your contributions. :)

**Pull request merged**
